package de.tyro.mcnetwork.simulation.packet.dsr;

import com.mojang.blaze3d.vertex.PoseStack;
import de.tyro.mcnetwork.client.RenderUtil;
import de.tyro.mcnetwork.simulation.IP;
import de.tyro.mcnetwork.simulation.packet.IProtocolPaket;
import de.tyro.mcnetwork.simulation.packet.NetworkPacket;
import net.minecraft.client.gui.Font;
import net.minecraft.world.phys.Vec2;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class DSRRouteRequest extends NetworkPacket implements IProtocolPaket {
    // A unique value generated by the initiator (original sender) of
    // the Route Request.  Nodes initiating a Route Request generate a
    // new Identification value for each Route Request, for example
    // based on a sequence number counter of all Route Requests
    // initiated by the node.
    //
    // This value allows a receiving node to determine whether it has
    // recently seen a copy of this Route Request.  If this
    // Identification value (for this IP Source address and Target
    // Address) is found by this receiving node in its Route Request
    // Table (in the cache of Identification values in the entry there
    // for this initiating node), this receiving node MUST discard the
    // Route Request.  When a Route Request is propagated, this field
    // MUST be copied from the received copy of the Route Request
    // being propagated.
    final private int identificationValue;

    // The address of the node that is the target of the Route Request.
    private IP targetAddress;

    // Address[i] is the IPv4 address of the i-th node recorded in the
    // Route Request option.  The address given in the Source Address
    // field in the IP header is the address of the initiator of the
    // Route Discovery and MUST NOT be listed in the Address[i]
    // fields; the address given in Address[1] is thus the IPv4
    // address of the first node on the path after the initiator.  The
    // number of addresses present in this field is indicated by the
    // Opt Data Len field in the option (n = (Opt Data Len - 6) / 4).
    // Each node propagating the Route Request adds its own address to
    // this list, increasing the Opt Data Len value by 4 octets.
    List<IP> addresses;

    public DSRRouteRequest(IP originatorIP, IP targetAddress, int identificationValue) {
        super(originatorIP, IP.BROADCAST);

        this.targetAddress = targetAddress;
        this.identificationValue = identificationValue;
        addresses = new ArrayList<>();
    }

    public DSRRouteRequest(UUID uuid, IP originatorIP, IP destinationIP, int identificationValue, IP targetAddress, List<IP> addresses) {
        super(uuid, originatorIP, destinationIP);
        this.identificationValue = identificationValue;
        this.targetAddress = targetAddress;
        this.addresses = addresses;
    }

    @Override
    public DSRRouteRequest copy() {
        return new DSRRouteRequest(getId(), getOriginatorIP(), getDestinationIP(), identificationValue, targetAddress, new ArrayList<>(addresses));
    }

    public void setTargetAddress(IP targetAddress) {
        this.targetAddress = targetAddress;
    }

    public List<IP> getAddresses() {
        return addresses;
    }

    public Integer getIdentificationValue() {
        return identificationValue;
    }

    public IP getTargetAddress() {
        return targetAddress;
    }

    public IP getSourceAddress() {
        return getOriginatorIP();
    }

    public void addAddress(IP ip) {
        addresses.add(ip);
    }

    public List<IP> getRouteToHere() {
        var list = new ArrayList<>(addresses);
        list.addFirst(getSourceAddress());
        return list;
    }


    @Override
    protected void renderPacketContent(RenderUtil renderer, PoseStack poseStack, float width) {
        var pose = renderer.getPoseStack();
        var font = renderer.getFont();
        pose.scale(0.5f,0.5f,0.5f);

        width *= 2;

        int y = 0;

        renderer.drawStringWithAlphaColor(RenderUtil.Align.LEFT, "IdentificationValue", width, y);
        renderer.drawStringWithAlphaColor(RenderUtil.Align.RIGHT, String.valueOf(identificationValue), width, y);
        y+= 10;

        renderer.drawStringWithAlphaColor(RenderUtil.Align.LEFT, "Target", width, y);
        renderer.drawStringWithAlphaColor(RenderUtil.Align.RIGHT, targetAddress.toString(), width, y);
        y+= 10;

        renderer.drawCollectionAsString(RenderUtil.Align.RIGHT, addresses, (int) width - font.width("Target") + 5, renderer.getTextColorFromAlpha(), width, y);
    }

    @Override
    public Vec2 getRenderSize(Font font) {
        var superSize = super.getRenderSize(font);
        var thisWidth = Math.min(100, font.width(addresses.toString())) / 2;
        return new Vec2(Math.max(superSize.x, thisWidth), superSize.y + 15);
    }
}
