package de.tyro.mcnetwork.routing.packet.dsr;

import de.tyro.mcnetwork.routing.IP;
import de.tyro.mcnetwork.routing.packet.IProtocolPaket;
import de.tyro.mcnetwork.routing.packet.NetworkPacket;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class DSRRouteRequest extends NetworkPacket implements IProtocolPaket {
    // A unique value generated by the initiator (original sender) of
    // the Route Request.  Nodes initiating a Route Request generate a
    // new Identification value for each Route Request, for example
    // based on a sequence number counter of all Route Requests
    // initiated by the node.
    //
    // This value allows a receiving node to determine whether it has
    // recently seen a copy of this Route Request.  If this
    // Identification value (for this IP Source address and Target
    // Address) is found by this receiving node in its Route Request
    // Table (in the cache of Identification values in the entry there
    // for this initiating node), this receiving node MUST discard the
    // Route Request.  When a Route Request is propagated, this field
    // MUST be copied from the received copy of the Route Request
    // being propagated.
    final private int identificationValue;

    // The address of the node that is the target of the Route Request.
    private IP targetAddress;

    // Address[i] is the IPv4 address of the i-th node recorded in the
    // Route Request option.  The address given in the Source Address
    // field in the IP header is the address of the initiator of the
    // Route Discovery and MUST NOT be listed in the Address[i]
    // fields; the address given in Address[1] is thus the IPv4
    // address of the first node on the path after the initiator.  The
    // number of addresses present in this field is indicated by the
    // Opt Data Len field in the option (n = (Opt Data Len - 6) / 4).
    // Each node propagating the Route Request adds its own address to
    // this list, increasing the Opt Data Len value by 4 octets.
    List<IP> addresses;

    public DSRRouteRequest(IP originatorIP, IP targetAddress, int identificationValue) {
        super(originatorIP, IP.BROADCAST);

        this.targetAddress = targetAddress;
        this.identificationValue = identificationValue;
        addresses = new ArrayList<>();
    }

    public DSRRouteRequest(UUID uuid, IP originatorIP, IP destinationIP, int identificationValue, IP targetAddress, List<IP> addresses) {
        super(uuid, originatorIP, destinationIP);
        this.identificationValue = identificationValue;
        this.targetAddress = targetAddress;
        this.addresses = addresses;
    }

    @Override
    public DSRRouteRequest copy() {
        return new DSRRouteRequest(getId(), getOriginatorIP(), getDestinationIP(), identificationValue, targetAddress, new ArrayList<>(addresses));
    }

    public void setTargetAddress(IP targetAddress) {
        this.targetAddress = targetAddress;
    }

    public List<IP> getAddresses() {
        return addresses;
    }

    public Integer getIdentificationValue() {
        return identificationValue;
    }

    public IP getTargetAddress() {
        return targetAddress;
    }

    public IP getSourceAddress() {
        return getOriginatorIP();
    }

    public void addAddress(IP ip) {
        addresses.add(ip);
    }

    public List<IP> getRouteToHere() {
        var list = new ArrayList<>(addresses);
        list.addFirst(getSourceAddress());
        return list;
    }
}
